id: P007039
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS56008
  title: མངའ་རིས་ཆོས་འབྱུང་གངས་ལྗོངས་མཛེས་རྒྱན
  author: ''
  volumes:
    2b09b0522e394b50bde843532958198b:
      image_group_id: I1GS56011
      title: Volume 1 of mnga' ris chos 'byung gangs ljongs mdzes rgyan
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
