id: P007039
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS56008
  title: མངའ་རིས་ཆོས་འབྱུང་གངས་ལྗོངས་མཛེས་རྒྱན
  author: ''
  volumes:
    70b0f749b7224095afccb872c7629b3c:
      image_group_id: I1GS56011
      title: ''
      volume_number: 1
      total_pages: 534
ebook_metadata:
  title: མངའ་རིས་ཆོས་འབྱུང་གངས་ལྗོངས་མཛེས་རྒྱན
  author: ''
  sku: P007039
  cover: cover.jpg
  layers:
  - pagination
