id: I24BEBF32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:00:53+00:00'
last_modified: '2022-06-08T13:33:16.410651+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS56008
  title: མངའ་རིས་ཆོས་འབྱུང་གངས་ལྗོངས་མཛེས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '0575':
      image_group_id: I1GS56011
      title: Volume 1 of mnga' ris chos 'byung gangs ljongs mdzes rgyan
      total_pages: 534
      order: 1
      base_file: 0575.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
